### PR TITLE
Skip noqa comments

### PR DESCRIPTION
**Pull request by 3n-k1**
`noqa` comments allow skipping certain flake8 codes on a line. Unfortunately, both `noqa` and the flake8 codes are not recognized as words (because they aren't). This change skips checking comment lines that begin with `noqa: `

### CODE REVIEW

**Comment by 3n-k1** [comment]
Whoops, I'll fix the linting.

I can also add tests, but I think it's a pretty small change.

**Comment by 3n-k1** [comment]
So, flake8 is complaining about the [complexity](https://www.flake8rules.com/rules/C901.html) of the function, which I can understand, but removing the nested `if` still triggers C901, and I can't think of a way to refactor without making the function hard to read. I'll force push an update, please tell me if you think it's acceptable.

**Comment by 3n-k1** [comment]
I apologize, it's late and I keep making silly little errors.

**Comment by 3n-k1** [comment]
i forgot to add in the index on the `.split()` call. fixed that.

i also figured out a way to reduce function complexity. in the `elif` statement on line 159, we can also check to see if the comment token's value starts with "noqa:".

there are merge conflicts because i forgot to fix those locally. mind telling me if this looks good?

**Comment by 3n-k1** [comment]
ah, completely forgot that! gimme a bit, i won't be able to write code for a few hours :p

**Comment by 3n-k1** [comment]
oh, i have made a huge mistake

**Comment by 3n-k1** [comment]
oh god and there are still conflicts, ugh.

@MichaelAquilina are you alright if i just open a new PR and redo everything? i have *no* idea how to fix this lol

**Comment by MichaelAquilina** [comment]
Yep no problem go ahead :)

**Comment by 3n-k1** [comment]
cool, thanks lol

**Pull request closed without merging**
